In [4]:
## Different types of python Modules used in ML & DS
"""
numpy, scipy  = mathematical computation
pandas = I/O , data cleaning, manipulation, exploration
mathplotlib, seabron = data visualization

scikit-learn, sklearn - machine learining algorithms
Tensorflow, theano - Advance ML, Deep Learning
keras, Pytorch = Deep Learning

NLTK, Textblob,spacy = NLP
opencv, skimage = image processing

Flask, Django = Web application development
QT, tkiner = Desktop application development
"""

&#39;\nnumpy, scipy  = mathematical computation\npandas = I/O , data cleaning, manipulation, exploration\nmathplotlib, seabron = data visualization\n\nscikit-learn sklearn - machine learining algorithms\nTensorflow, theano - Advance ML, Deep Learning\nkeras, Pytorch = Deep Learning\n\nNLTK, Textblob,spacy = NLP\nopencv, skimage = image processing\n\nFlask, Django = Web application development\nQT, tkiner = Desktop application development\n&#39;

In [25]:
# DEclaring Arrays using numpy

# Statistical analysis using numpy

# manipulations of array

# linear Algebra using numpy

a = [1,3,5]
b = [4,7,9]
c=a+b
print(c) ## Can't add two lists

# DEclaring Arrays using numpy
import numpy
a=numpy.array([2,4,5])
b=numpy.array([4,6,7])
c=a+b
print(c)

print(" \n")

## Multi dimentional array
#x=numpy.array([4,5,6])
x=numpy.array([[4,5,8],[2,6,2],[4,8,3]])
print(x)
print(x.size) # Size of the array

print (x.shape) # Shape of the Array

## printing required columns
print(x[0,0]) # 1st column 1st row
print(x[1,0]) # 2nd column 1st row

#### all are same
print(x[2,0:3])
print(x[2,:])
print(x[2])

print(" \n")

print(x[:,2]) # to get 2nd column from an array

print(" \n")
x[:,1]=[7,4,6] ### new valumes in 1st column
print(x)


[1, 3, 5, 4, 7, 9]
[ 6 10 12]
 

[[4 5 8]
 [2 6 2]
 [4 8 3]]
9
(3, 3)
4
2
[4 8 3]
[4 8 3]
[4 8 3]
 

[8 2 3]
 

[[4 7 8]
 [2 4 2]
 [4 6 3]]


In [32]:
#to add 0th col and 1st col store result in 2nd column
import numpy
x=numpy.array([[4,5,8],[2,6,2],[4,8,3]])
print(x)
print(" \n")
x[:,2]=x[:,0]+x[:,1]
print(x)
print(" \n")
x[:,2]=x[:,0+1] ######### NOT WORK
print(x)
print(" \n")

[[4 5 8]
 [2 6 2]
 [4 8 3]]
 

[[ 4  5  9]
 [ 2  6  8]
 [ 4  8 12]]
 

[[4 5 5]
 [2 6 6]
 [4 8 8]]
 



In [54]:
#Declaring numpy array
x=numpy.ones(5)
print(x)
print(" \n")


x=numpy.ones((2,5))
print(x)
print(" \n")

x=numpy.zeros((4,5))
print(x)
print(" \n")

x=numpy.array([[1,3],[1,2,3],[1,2,4,5]]) ##Different type of array size
print(x)
print(" \n")


x=2*numpy.ones((2,4)) ### using 2 matix
print(x)
print(" \n")

x=numpy.arange(12) ###Array starts 1 to 11 sequential array
print(x)
print(" \n")

x=numpy.arange(8,12)
print(x)
print(" \n")

x=numpy.arange(2,12,2)
print(x)
print(" \n")


x=numpy.linspace(start=4,stop=6,num=4) ### equally spaced values
print(x)
print(" \n")

x=numpy.linspace(1,9,12)
print(x)
print('\n')


x=numpy.logspace(0,4,4)
print(x)
print(' \n')


x=numpy.logspace(0,4,5) ### Log space from 0 to 4 with 5 positions 
x=x.astype('int32')
print(x)
print(' \n')


x=numpy.logspace(0,4,5,dtype='int32')
print(x)
print(' \n')

print(numpy.log(10))

print(numpy.log(10000))


[1. 1. 1. 1. 1.]
 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
 

[list([1, 3]) list([1, 2, 3]) list([1, 2, 4, 5])]
 

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]]
 

[ 0  1  2  3  4  5  6  7  8  9 10 11]
 

[ 8  9 10 11]
 

[ 2  4  6  8 10]
 

[4.         4.66666667 5.33333333 6.        ]
 

[1.         1.72727273 2.45454545 3.18181818 3.90909091 4.63636364
 5.36363636 6.09090909 6.81818182 7.54545455 8.27272727 9.        ]


[1.00000000e+00 2.15443469e+01 4.64158883e+02 1.00000000e+04]
 

[    1    10   100  1000 10000]
 

[    1    10   100  1000 10000]
 

2.302585092994046
9.210340371976184


In [59]:
#statistical analysis using numpy
x=numpy.array([[7,5,8],[2,6,2],[4,8,3]])
print(x)
print(x.min()) ### Row operation
print(x.max()) ### Row operation
print(x.mean()) ### Row operation


########Column operation
print(' \n')

print(x.min(axis=0))
print(x.max(axis=0))
print(x.mean(axis=0))
print(x.mean(axis=1))

print(' \n')



[[7 5 8]
 [2 6 2]
 [4 8 3]]
2
8
5.0
 

[2 5 2]
[7 8 8]
[4.33333333 6.33333333 4.33333333]
[6.66666667 3.33333333 5.        ]


In [66]:

### VAriance = Spread of the data across mean
#delhi temp Gassian curve 
d = numpy.array([18,19,21,23,23,24,40,23,43,34,23,32,32,33,43,45,44,29,22,27])
print(d.mean())
print(numpy.var(d))

print('\n')

m = numpy.array([22,21,22,22.5,22.8,26,29,28,21,24,27,30])
print(m.mean())
print(numpy.var(m)) ## if variance is 0 or near to 0 it mean it is not impacting the feature 
# example customer age in an example data of customer leaving data
# if in case of some image, if variance of pixcel is zero then no image,if it is high/medium then some images would be there

print('\n')
# Standard deviation = square root of variance
print(numpy.std(d))
print(numpy.std(m))

29.9
77.19


24.608333333333334
9.60409722222222


8.78578397184907
3.0990477928264064


In [74]:
### Reshape
d = numpy.array([18,19,21,23,23,24,40,23,43,34,23,32,32,33,43,45,44,29,22,27])
print(d.size)
d=d.reshape(5,4)
print(d)
print(d.shape)
print(d.dtype)
d=d.astype('float32')
print(d)
print(d.dtype)
print('\n')



20
[[18 19 21 23]
 [23 24 40 23]
 [43 34 23 32]
 [32 33 43 45]
 [44 29 22 27]]
(5, 4)
int32
[[18. 19. 21. 23.]
 [23. 24. 40. 23.]
 [43. 34. 23. 32.]
 [32. 33. 43. 45.]
 [44. 29. 22. 27.]]
float32


[[ 1.00000000e+00  6.66133815e-16 -5.00000000e-01]
 [ 1.03333333e+01 -1.33333333e+00 -4.33333333e+00]
 [-8.00000000e+00  1.00000000e+00  3.50000000e+00]]
[[ 1.00000000e+00 -2.10942375e-15 -2.22044605e-15]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 8.88178420e-16  4.44089210e-15  1.00000000e+00]]


In [79]:
#Linear Algebra using numpy
m=numpy.matrix([[2,3,4],[9,3,5],[2,6,8]])
print(numpy.linalg.inv(m))
print('\n')

print(numpy.linalg.inv(m)*m)
print('\n')

## Ranking of matrix
print(numpy.linalg.matrix_rank(m))
print('\n')


#Eigen Vectors
print(numpy.linalg.eig(m))
print('\n')

[[ 1.00000000e+00  6.66133815e-16 -5.00000000e-01]
 [ 1.03333333e+01 -1.33333333e+00 -4.33333333e+00]
 [-8.00000000e+00  1.00000000e+00  3.50000000e+00]]


[[ 1.00000000e+00 -2.10942375e-15 -2.22044605e-15]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 8.88178420e-16  4.44089210e-15  1.00000000e+00]]


3


(array([14.29938469, -1.56713369,  0.267749  ]), matrix([[-0.37573664, -0.15318135, -0.11469634],
        [-0.60854925,  0.85127959, -0.77024249],
        [-0.69892045, -0.5018551 ,  0.62735258]]))


In [80]:
#linear algebra 
#2x+3y=13
#4x-y=5

a=[[2,3],[4,-1]]
b=[13,5]
numpy.linalg.solve(a,b)

array([2., 3.])